import type { Charm } from "./types";

const toId = (name: string) =>
  name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

export const allCharms: Charm[] = [
  // Essence 1
  {
    id: toId("Flawless Handiwork Method"),
    name: "Flawless Handiwork Method",
    cost: "3m",
    description: "Craft rolls supplemented by this Charm reroll 10s until no more appear.",
    minCraft: 1,
    minEssence: 1,
    effect: { type: "reroll_tens" },
  },
  {
    id: toId("First Movement of the Demiurge"),
    name: "First Movement of the Demiurge",
    cost: "5m",
    description: "Reroll all failed dice (1-6) on a Craft roll.",
    minCraft: 4,
    minEssence: 2,
    effect: { type: "reroll_failures" },
  },
  {
    id: toId("Tireless Workhorse Method"),
    name: "Tireless Workhorse Method",
    description: "Permanently grants two major project slots per dot of Essence the Solar possesses.",
    minCraft: 2,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Triumph-Forging Eye"),
    name: "Triumph-Forging Eye",
    cost: "Free (Once per week)",
    description: "Once per week, applies a free full Craft Excellency to any one roll.",
    minCraft: 2,
    minEssence: 1,
    effect: { type: "custom" },
  },
   {
    id: toId("Supreme Masterwork Focus"),
    name: "Supreme Masterwork Focus",
    description: "A multi-tiered charm that improves the quality of successes on crafting rolls.",
    minCraft: 3,
    minEssence: 1,
    effect: { type: "custom" },
    subEffects: [
       {
        id: toId("Supreme Masterwork Focus-1"),
        name: "Level 1: Double Nines",
        cost: "5m, 1wp",
        description: "Supplements (Attribute + Craft) rolls for basic/major projects with double 9s.",
        minCraft: 3,
        minEssence: 1,
        effect: { type: "double_success", value: 9 },
      },
      {
        id: toId("Supreme Masterwork Focus-2"),
        name: "Level 2: Double Eights",
        cost: "5m, 1wp, 1gxp",
        description: "Repurchase for double 8s on basic, major, or superior project rolls.",
        minCraft: 5,
        minEssence: 2,
        effect: { type: "double_success", value: 8 },
      },
      {
        id: toId("Supreme Masterwork Focus-3"),
        name: "Level 3: Double Sevens",
        cost: "2m, 1wxp",
        description: "A third repurchase grants double 7s on any (Attribute + Craft) roll.",
        minCraft: 5,
        minEssence: 3,
        effect: { type: "double_success", value: 7 },
      }
    ]
  },
  {
    id: toId("Brass Scales Falling"),
    name: "Brass Scales Falling",
    description: "For each 10 on a Craft roll (without Craft Excellency), earns a silver point, up to (Essence * 2) points. Can be repurchased to increase the cap to (Essence * 3).",
    minCraft: 3,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Efficient Craftsman Technique"),
    name: "Efficient Craftsman Technique",
    description: "Permanently reduces the cost of temporary major slots to three silver points.",
    minCraft: 3,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Craftsman Needs No Tools"),
    name: "Craftsman Needs No Tools",
    cost: "5m",
    description: "Allows starting and completing basic/major projects rapidly without tools or workshop, shaping material directly. Reduces cost by 2 motes if tools are used. Does not significantly speed superior/legendary projects.",
    minCraft: 3,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Crack-Mending Technique"),
    name: "Crack-Mending Technique",
    cost: "5m",
    description: "Repairs extremely damaged objects. Can lower repair difficulty by 1 for fragmented Artifacts.",
    minCraft: 3,
    minEssence: 1,
    effect: { type: "lower_repair_difficulty", value: 1 },
  },
  {
    id: toId("Arete-Shifting Prana"),
    name: "Arete-Shifting Prana",
    cost: "5m, 1wp",
    description: "Allows temporary conversion of dots from one known Craft into a conceptually related Craft ability for one basic or major project.",
    minCraft: 4,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Red Anvils Ringing"),
    name: "Red Anvils Ringing",
    description: "Increases silver points gained from each basic objective by one.",
    minCraft: 4,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Time Heals Nothing"),
    name: "Time Heals Nothing",
    cost: "3m",
    description: "Instantly creates a temporary major project slot for repairs.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Shattering Grasp"),
    name: "Shattering Grasp",
    cost: "10m, 1wp",
    description: "Allows disassembling materials and objects without tools.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Durability-Enhancing Technique"),
    name: "Durability-Enhancing Technique",
    cost: "10m",
    description: "Permanently increases an object's damage difficulty by two or (Essence), whichever is larger.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Blood Diamond Sweat"),
    name: "Blood Diamond Sweat",
    description: "Gains one additional craft point for every basic objective completed during a repair.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Chains Fall Away"),
    name: "Chains Fall Away",
    description: "Gains one gold point each time all three basic objectives on any Craft project are achieved.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },
  {
    id: toId("Peerless Paragon of Craft"),
    name: "Peerless Paragon of Craft",
    description: "Upon purchase and at the end of each story, rolls a free full (Intelligence + Craft) Excellency, converting successes to silver points, and 10s also reward a gold point.",
    minCraft: 5,
    minEssence: 1,
    effect: { type: "custom" },
  },

  // Essence 2
  {
    id: toId("Experiential Conjuring of True Void"),
    name: "Experiential Conjuring of True Void",
    cost: "5m, 1wp",
    description: "Used after a roll, grants one automatic success and (Essence) non-Charm dice.",
    minCraft: 3,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Bright-Forging Prana"),
    name: "Bright-Forging Prana",
    cost: "10m, 1wp",
    description: "Once per story, allows using (Essence or 3) Craft Charms not yet learned.",
    minCraft: 3,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Unbroken Image Focus"),
    name: "Unbroken Image Focus",
    cost: "5m, 1wp",
    description: "After a roll, adds (Essence + successes on initial roll) additional successes.",
    minCraft: 4,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Design Beyond Limit"),
    name: "Design Beyond Limit",
    cost: "15m, 1wp, 8xp",
    description: "Reforges an Artifact weapon to grant one new inactive Emerald, Sapphire, and Adamant Evocation.",
    minCraft: 4,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Chaos-Resistance Preparation"),
    name: "Chaos-Resistance Preparation",
    cost: "10m, 1wp",
    description: "Treats an object to protect it from Wyld effects.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Thousand-Forge Hands"),
    name: "Thousand-Forge Hands",
    cost: "10m, 1wp",
    description: "Greatly speeds the initial design and forging work for superior or legendary projects.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Object-Strengthening Touch"),
    name: "Object-Strengthening Touch",
    cost: "15m, 1wp",
    description: "Infuses an object with hardening Essence, increasing its destruction difficulty by (Solar's Essence + 1).",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Breach-Healing Method"),
    name: "Breach-Healing Method",
    cost: "20m, 1wp",
    description: "Establishes an Essence field that provides a dice bonus and reduces repair difficulty.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Dragon Soul Emergence"),
    name: "Dragon Soul Emergence",
    description: "Grants one permanent superior project slot. Can be purchased up to (Essence) times.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Sublime Transference"),
    name: "Sublime Transference",
    cost: "1m",
    description: "Allows rearrangement of crafting points: 2sxp to 1gxp, 2gxp to 1wxp, 1wxp to 2gxp, and 1gxp to 2sxp.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Supreme Celestial Focus"),
    name: "Supreme Celestial Focus",
    description: "Allows raising an additional Craft rating from one to five using gold points instead of experience.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Supreme Perfection of Craft"),
    name: "Supreme Perfection of Craft",
    description: "Upon purchase, earns gold and silver points for every Craft Ability rated at 5. This bonus recurs daily.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },
  {
    id: toId("Ages-Echoing Wisdom"),
    name: "Ages-Echoing Wisdom",
    description: "Grants gold points equal to permanent major slots upon purchase, and again at the end of each story.",
    minCraft: 5,
    minEssence: 2,
    effect: { type: "custom" },
  },

  // Essence 3
  {
    id: toId("Divine Transcendence of Craft"),
    name: "Divine Transcendence of Craft",
    description: "Instantly grants three white points when purchased, and five additional white points at the end of each story.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Mind-Expanding Meditation"),
    name: "Mind-Expanding Meditation",
    cost: "1m/die",
    description: "Invoked before a roll, allows raising the dice cap at 1sxp per die, up to current Craft rating.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Essence-Forging Kata"),
    name: "Essence-Forging Kata",
    cost: "10m, 1wp",
    description: "While active for one day, every two motes committed discounts the cost of the Craft Excellency by one.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Inspiration-Renewing Vision"),
    name: "Inspiration-Renewing Vision",
    cost: "10m, 1wp",
    description: "Supplements a superior or legendary Craft roll so it does not count towards the project's terminus.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Divine Inspiration Technique"),
    name: "Divine Inspiration Technique",
    cost: "5m",
    description: "For every three successes on a Craft roll, earns an additional non-Charm die. This effect is recursive.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Words-as-Workshop Method"),
    name: "Words-as-Workshop Method",
    cost: "15m, 1wp",
    description: "Summons Artifact tools for the current task.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Copper Spider Conception"),
    name: "Copper Spider Conception",
    cost: "10m, 1wp",
    description: "Lowers the cost of creating a superior slot by two gold points and two major slots.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Summit-Piercing Touch"),
    name: "Summit-Piercing Touch",
    cost: "10m",
    description: "Allows a 2-dot Artifact superior project to be placed in an unused major slot.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Clay and Breath Practice"),
    name: "Clay and Breath Practice",
    description: "On each interval of a superior roll, if successes exceed the finishing price, the Solar earns silver points.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Spirit-Gathering Industry"),
    name: "Spirit-Gathering Industry",
    description: "Permanently reduces the cost to finish a superior project by (Essence) gold points, to a minimum of three.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Vice-Miracle Technique"),
    name: "Vice-Miracle Technique",
    cost: "20m, 2wp, 5gxp",
    description: "Once per season, produces a finished 2-dot Artifact without gold point cost or Craft points earned.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("The Art of Permanence"),
    name: "The Art of Permanence",
    cost: "10m, 1wp",
    description: "Infuses basic and major projects with magic, making them endure forever.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Realizing the Form Supernal"),
    name: "Realizing the Form Supernal",
    description: "When repairing an Artifact, reduces repair difficulty by one and the goal number.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },
  {
    id: toId("Celestial Reforging Technique"),
    name: "Celestial Reforging Technique",
    cost: "20m, 1wp, 10xp",
    description: "Reshapes an Exalted weapon's current active Evocations.",
    minCraft: 5,
    minEssence: 3,
    effect: { type: "custom" },
  },

  // Essence 4
  {
    id: toId("Holistic Miracle Understanding"),
    name: "Holistic Miracle Understanding",
    description: "Enhances its prerequisite: if the dice from the initial roll produce successes, add three more non-Charm dice.",
    minCraft: 5,
    minEssence: 4,
    effect: { type: "custom" },
  },
  {
    id: toId("Horizon-Unveiling Insight"),
    name: "Horizon-Unveiling Insight",
    description: "Permanently raises the terminus of superior and legendary projects to seven.",
    minCraft: 5,
    minEssence: 4,
    effect: { type: "custom" },
  },
  {
    id: toId("Unwinding Gyre Meditation"),
    name: "Unwinding Gyre Meditation",
    cost: "20m, 2wp, 10gxp",
    description: "Reduces goal number, adds an interval, and increases gold point bonus on next identical Artifact.",
    minCraft: 5,
    minEssence: 4,
    effect: { type: "custom" },
  },
  {
    id: toId("God-Forge Within"),
    name: "God-Forge Within",
    description: "Grants two permanent legendary project slots per purchase.",
    minCraft: 5,
    minEssence: 4,
    effect: { type: "custom" },
  },

  // Essence 5
  {
    id: toId("Dual Magnus Prana"),
    name: "Dual Magnus Prana",
    cost: "30m, 2wp, 10gxp, 2wxp",
    description: 'Upon incapacitation, reveals the "slain" character to be a perfect double.',
    minCraft: 5,
    minEssence: 5,
    effect: { type: "custom" },
  },
  {
    id: toId("Wonder-Forging Genius"),
    name: "Wonder-Forging Genius",
    cost: "20m, 2wp, all wxp",
    description: "When ten or more legendary projects are underway, completes one without rolls or craft points.",
    minCraft: 5,
    minEssence: 5,
    effect: { type: "custom" },
  },
  {
    id: toId("Sun-Heart Tenacity"),
    name: "Sun-Heart Tenacity",
    description: "Provides ten automatic non-Charm successes to the next superior or legendary project when a legendary project is completed.",
    minCraft: 5,
    minEssence: 5,
    effect: { type: "custom" },
  },
  {
    id: toId("Spirit-Stoking Elevation"),
    name: "Spirit-Stoking Elevation",
    description: "Allows replacing experience point costs of certain Charms with white points.",
    minCraft: 5,
    minEssence: 5,
    effect: { type: "custom" },
  },
  {
    id: toId("Exegesis of the Distilled Form"),
    name: "Exegesis of the Distilled Form",
    cost: "1m",
    description: 'After completing five legendary projects, expends all white points, rolling them for experience points.',
    minCraft: 5,
    minEssence: 5,
    effect: { type: "custom" },
  },
];

    